{% set data = load_setup_py_data() %}

package:
    name    : ophyd_ads
    version : {{ data.get('version') }}

source:
    path: ..

build:
    number: 1
    noarch: python

requirements:
    build:
      - python >=3.6
      - pip
    run:
      - ophyd >=1.4
      - pyads
      - pydm

test:
    imports:
      - ophyd_ads

about:
  home: https://github.com/pcdshub/ophyd-ads
  license: SLAC Open License
  summary: ophyd integration with Beckhoff TwinCAT 3 via pyads
